"""
Script for making a truly horrific switch statement in Storm for creating tags in Synapse during address ingest.
I'll atone for my sins later.
"""

ransomwhere_labels = ["7ev3n",
                      "AES-NI",
                      "APT",
                      "AdamLocker",
                      "Akira",
                      "Ako",
                      "AlbDecryptor",
                      "Alphabet",
                      "AngleWare",
                      "Avaddon",
                      "Avos Locker",
                      "AvosLocker",
                      "BadEncrypt",
                      "Badblock",
                      "Bagli",
                      "Bitpaymer / DoppelPaymer",
                      "Black Basta",
                      "Black Kingdom",
                      "Black Mamba",
                      "Black Ruby",
                      "BlackCat",
                      "BlackFeather",
                      "BlackMatter",
                      "BlackRouter",
                      "BlackSuit",
                      "Bucbi",
                      "Buddy",
                      "CTB-Locker",
                      "Chimera",
                      "ChupaCabra",
                      "ComradeCircle",
                      "Conti",
                      "CryptConsole",
                      "CryptXXX",
                      "CryptoHost",
                      "CryptoLocker",
                      "CryptoSweetTooth",
                      "CryptoTorLocker2015",
                      "Cryptohitman",
                      "Cryptowall",
                      "Cuba",
                      "CyberSpLiTTER",
                      "DMALocker",
                      "DMALockerv3",
                      "DarkSide",
                      "DeadBolt",
                      "DecryptIomega",
                      "Decryptiomega",
                      "Domino",
                      "Doxware",
                      "EDA2",
                      "Ecovector",
                      "Egregor",
                      "Encrpt3d",
                      "Exotic",
                      "FakeGlobe",
                      "File-Locker",
                      "Filecry",
                      "FireCrypt",
                      "Flyper",
                      "Git",
                      "Globe",
                      "GlobeImposter",
                      "Globev2",
                      "Globev3",
                      "Gula",
                      "HC6/HC7",
                      "HelloKitty",
                      "Hive",
                      "JigSaw",
                      "Jigsaw",
                      "Karakurt",
                      "Kelly",
                      "LamdaLocker",
                      "LockBit 2.0",
                      "LockBit",
                      "LockOn",
                      "Lockbit",
                      "Locky",
                      "Makop",
                      "Mallox",
                      "Maui",
                      "MedusaLocker",
                      "MountLocker",
                      "Nemucod",
                      "Netwalker (Mailto)",
                      "NoobCrypt",
                      "NotNevada",
                      "NotPetya",
                      "NullByte",
                      "PayDay",
                      "Pgpsnippet",
                      "Philadelphia",
                      "Phobos",
                      "Phoenix",
                      "PopCornTime",
                      "Predator",
                      "Qlocker",
                      "Quantum",
                      "Qweuirtksd",
                      "REKTLocker",
                      "REvil / Sodinokibi",
                      "RagnarLocker",
                      "RansomPlus",
                      "Ransomnix",
                      "Ranzy Locker",
                      "Razy",
                      "Rush/Sanction",
                      "Ryuk",
                      "Sam",
                      "SamSam",
                      "Spora",
                      "StorageCrypter",
                      "Stupid",
                      "SunCrypt",
                      "SynAck",
                      "Tejodes",
                      "TeslaCrypt",
                      "ThunderCrypt",
                      "TowerWeb",
                      "TripleM",
                      "Trump Locker",
                      "Unlabeled",
                      "Vega / Jamper / Buran",
                      "VenusLocker",
                      "Vevolocker",
                      "WannaCry",
                      "WannaRen",
                      "WannaSmile",
                      "XLocker",
                      "XLockerv5.0",
                      "XTPLocker",
                      "Xorist",
                      "ZeroLocker",
                      "Zyka",
                      "darkangels",
                      "l1me_expl0it"]


def build_switch_block(ransomwhere_label: str):
    label = ransomwhere_label.lower()
    label = label.replace(" ", "_")
    label = label.replace(".", "_")

    output = """"LABEL": {
    [+#rep.ransomwhere.label]
}""".replace("LABEL", ransomwhere_label).replace("label", label)
    return output


# print(build_switch_block("XLockerv5.0"))
# print(build_switch_block("Lockbit"))
# print(build_switch_block("LockBit"))
# print(build_switch_block("LockBit 2.0"))
# print(build_switch_block("VenusLocker"))
# print(build_switch_block("Vega / Jamper / Buran"))

for entry in ransomwhere_labels:
    print(build_switch_block(entry))
